all: pendulum crash pung

clean:
	rm -rf .o*
	rm -rf pendulum
	rm -rf crash
	rm -rf pung

pendulum: hello4.c
	gcc -o pendulum hello4.c -lcurses -lm

crash: hello44.c
	gcc -o crash hello44.c -lcurses -lm

pung: pongg.c
	gcc -o pung pongg.c -lncurses

